<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitee7375b27820910c52d0ce6dc517476d
{
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/src',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->fallbackDirsPsr4 = ComposerStaticInitee7375b27820910c52d0ce6dc517476d::$fallbackDirsPsr4;
            $loader->classMap = ComposerStaticInitee7375b27820910c52d0ce6dc517476d::$classMap;

        }, null, ClassLoader::class);
    }
}
